#ifndef _WII_ACCESSORY_CONFIG_H_
#define _WII_ACCESSORY_CONFIG_H_

#define WII_ACCESSORY_PORT GPIOB
#define WII_ACCESSORY_SCL_PIN GPIO_PIN_6
#define WII_ACCESSORY_SDA_PIN GPIO_PIN_7
#define WII_ACCESSORY_DETECT_PIN GPIO_PIN_5

#endif
